# Generated by Django 5.1.2 on 2024-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
