# Generated by Django 5.1.2 on 2024-11-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='units',
        ),
    ]
