# Generated by Django 5.1.2 on 2024-11-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_grade_finals_grade_alter_grade_midterm_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='finals_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='overall_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
